### ISSUE TITLE
BrowserStackLocal testing

### ISSUE THREAD

**Issue by pieterdt** [shoov/shoov-webdrivercss#22]
Hi,

How should I configure the visual-monitor test so that it uses BrowserstackLocal? Just running the binary doesn't seem to do the trick. I found some mentions that browserstack.local = "true" should be set somewhere, but couldn't find out where to configure this. Adding it in the browser capabilities didn't work.

Is there a way to make this work, or is it not supported?

thx

**Comment by amitaibu** [comment]
Hi @pieterdt , there are the [docs](http://shoov.io/tutorials/lesson1-install/) that might help you configure it. If not, let us know here.
